const { test, expect, _electron } = require('@playwright/test');
const http = require('node:http');
const net = require('node:net');
const fs = require('node:fs');
const os = require('node:os');
const path = require('node:path');

test('general browser opens local sites, searches, tabs, bookmarks and blocks popups', async () => {
  test.setTimeout(60000);
  const server = http.createServer((req, res) => {
    res.setHeader('Content-Type', 'text/html');
    if (req.url === '/next') return res.end('<title>Second page</title><h1>Second page</h1>');
    res.end('<title>Local test site</title><h1>Local test site</h1><a id="next" href="/next">Next</a><a id="blank" href="/next" target="_blank">New tab link</a><script>window.popupResult=window.open("https://popup.example.com/")</script><img src="https://doubleclick.net/ad.png">');
  });
  await new Promise((resolve) => server.listen(0, '127.0.0.1', resolve));
  const socks = net.createServer((socket) => socket.once('data', () => socket.write(Buffer.from([5, 0]))));
  await new Promise((resolve) => socks.listen(0, '127.0.0.1', resolve));
  const port = server.address().port;
  const profile = fs.mkdtempSync(path.join(os.tmpdir(), 'cinestream-browser-test-'));
  const env = { ...process.env, CINEMA_PROFILE_DIR: profile };
  delete env.ELECTRON_RUN_AS_NODE;
  let app;
  try {
    app = await _electron.launch({ args: ['.'], env, timeout: 20000 });
    const page = await app.firstWindow();
    await expect(page.locator('.tab')).toHaveCount(1);
    await expect(page.locator('#start-page')).toBeVisible();
    await page.locator('#url-input').fill(`localhost:${port}`);
    await page.locator('#url-input').press('Enter');
    await expect.poll(() => page.locator('#url-input').inputValue()).toBe(`http://localhost:${port}/`);
    await expect(page.locator('.tab-title')).toHaveText('Local test site');
    const pageHeight = await page.evaluate(() => {
      const view = document.querySelector('webview');
      return { outer: view.getBoundingClientRect().height, inner: view.shadowRoot.querySelector('iframe').getBoundingClientRect().height };
    });
    expect(pageHeight.outer).toBeGreaterThan(500);
    expect(pageHeight.inner).toBeGreaterThan(pageHeight.outer - 5);
    const state = await app.evaluate(async ({ BrowserWindow, webContents }) => {
      const prefs = (contents) => {
        const value = contents.getLastWebPreferences();
        return { sandbox: value.sandbox, contextIsolation: value.contextIsolation, nodeIntegration: value.nodeIntegration, webSecurity: value.webSecurity };
      };
      const guest = webContents.getAllWebContents().find((item) => item.getType() === 'webview');
      return { shell: prefs(BrowserWindow.getAllWindows()[0].webContents), guest: prefs(guest), persistent: guest.session.isPersistent(), popupResult: await guest.executeJavaScript('window.popupResult === null') };
    });
    expect(state.shell).toEqual({ sandbox: true, contextIsolation: true, nodeIntegration: false, webSecurity: true });
    expect(state.guest).toEqual(state.shell);
    expect(state.persistent).toBe(false);
    expect(state.popupResult).toBe(true);
    expect(await app.evaluate(({ BrowserWindow }) => BrowserWindow.getAllWindows().length)).toBe(1);
    await expect.poll(() => page.evaluate(() => window.cinemaApi.getBlockStats())).toMatchObject({ adsBlocked: expect.any(Number), popupsBlocked: expect.any(Number) });
    const protection = await page.evaluate(() => window.cinemaApi.getBlockStats());
    expect(protection.adsBlocked).toBeGreaterThan(0);
    await app.evaluate(({ webContents }) => webContents.getAllWebContents().find((item) => item.getType() === 'webview').executeJavaScript('document.getElementById("blank").click()'));
    await expect.poll(() => page.locator('#url-input').inputValue()).toBe(`http://localhost:${port}/next`);
    await expect(page.locator('.tab-title')).toHaveText('Second page');
    await expect(page.locator('.tab')).toHaveCount(1);
    await expect(page.locator('#btn-back')).toBeEnabled();
    await page.locator('#btn-back').click();
    await expect.poll(() => page.locator('#url-input').inputValue()).toBe(`http://localhost:${port}/`);
    await page.locator('#btn-forward').click();
    await expect.poll(() => page.locator('#url-input').inputValue()).toBe(`http://localhost:${port}/next`);
    await page.locator('#btn-bookmark').click();
    await expect(page.locator('#btn-bookmark')).toHaveText('★');
    await page.locator('#btn-home').click();
    await expect(page.locator('#start-page')).toBeVisible();
    await expect(page.locator('.quick-link').first()).toContainText('Second page');
    await page.locator('.quick-link').first().click();
    await expect(page.locator('.tab-title')).toHaveText('Second page');
    await page.locator('#new-tab').click();
    await expect(page.locator('.tab')).toHaveCount(2);
    await page.locator('#url-input').fill('a search term');
    await page.locator('#url-input').press('Enter');
    await expect.poll(() => page.locator('#url-input').inputValue()).toBe('https://duckduckgo.com/?q=a%20search%20term');
    await page.locator('#btn-menu').click();
    await page.getByRole('button', { name: /Settings & VPN/ }).click();
    await expect(page.locator('#local-ips')).not.toContainText('Checking local addresses');
    await expect(page.locator('#search-engine')).toHaveValue('duckduckgo');
    await page.locator('#search-engine').selectOption('brave');
    await expect(page.locator('#url-input')).toHaveAttribute('placeholder', /Brave Search/);
    await expect(page.locator('#proxy-mode')).toHaveValue('system');
    await page.locator('#proxy-mode').selectOption('manual');
    await page.locator('#proxy-host').fill('127.0.0.1');
    await page.locator('#proxy-port').fill('8080');
    await page.getByRole('button', { name: 'Apply connection' }).click();
    await expect.poll(() => page.evaluate(() => window.cinemaApi.getProxy())).toMatchObject({ mode: 'manual' });
    await page.locator('#proxy-mode').selectOption('system');
    await page.getByRole('button', { name: 'Apply connection' }).click();
    const onionBlocked = await page.evaluate(() => window.cinemaApi.navigate({ id: document.querySelector('webview.active').getWebContentsId(), url: 'example.onion' }).then(() => false, () => true));
    expect(onionBlocked).toBe(true);
    await page.locator('#proxy-mode').selectOption('tor');
    await page.locator('#tor-port').fill(String(socks.address().port));
    await page.getByRole('button', { name: 'Apply connection' }).click();
    await expect.poll(() => page.evaluate(() => window.cinemaApi.getProxy())).toMatchObject({ mode: 'tor', torPort: socks.address().port });
    expect(await app.evaluate(({ webContents }) => webContents.getAllWebContents().find((item) => item.getType() === 'webview').session.resolveProxy('http://example.onion/'))).toContain('SOCKS5');
    const ipBypassedTor = await page.evaluate(() => window.cinemaApi.checkPublicIp().then(() => true, () => false));
    expect(ipBypassedTor).toBe(false);
    await page.locator('#proxy-mode').selectOption('system');
    await page.getByRole('button', { name: 'Apply connection' }).click();
    await app.evaluate(({ webContents }, port) => webContents.getAllWebContents().find((item) => item.getType() === 'webview').session.cookies.set({ url: `http://localhost:${port}/`, name: 'temporary', value: 'present' }), port);
    expect(await app.evaluate(({ webContents }) => webContents.getAllWebContents().find((item) => item.getType() === 'webview').session.cookies.get({ name: 'temporary' }))).toHaveLength(1);
    await page.evaluate(() => window.cinemaApi.clearCache());
    expect(await app.evaluate(({ webContents }) => webContents.getAllWebContents().find((item) => item.getType() === 'webview').session.cookies.get({ name: 'temporary' }))).toHaveLength(0);
    await page.locator('#panel-close').click();
    await page.locator('#btn-home').click();
    await page.locator('#btn-menu').click();
    await page.getByRole('button', { name: /History this session/ }).click();
    await expect(page.locator('.panel-item')).not.toHaveCount(0);
    await page.getByRole('button', { name: 'Clear all history' }).click();
    await expect(page.locator('.panel-item')).toHaveCount(0);
    expect(await app.evaluate(({ webContents }) => webContents.getAllWebContents().filter((item) => item.getType() === 'webview').every((item) => !item.navigationHistory.canGoBack()))).toBe(true);
    await page.locator('#panel-close').click();
    await page.evaluate(() => localStorage.setItem('browser-search-engine', 'google'));
    await page.reload();
    await expect(page.locator('#url-input')).toHaveAttribute('placeholder', /DuckDuckGo/);
    await page.locator('#btn-menu').click();
    await page.getByRole('button', { name: /Settings & VPN/ }).click();
    await expect(page.locator('#search-engine')).toHaveValue('duckduckgo');
    await expect(page.locator('#search-engine option')).toHaveCount(2);
    await page.locator('#panel-close').click();
    await page.screenshot({ path: 'artifacts/browser-desktop.png' });
  } finally {
    if (app) await app.close();
    await new Promise((resolve) => server.close(resolve));
    await new Promise((resolve) => socks.close(resolve));
    fs.rmSync(profile, { recursive: true, force: true });
  }
});
