<script setup>
import {usePage,useForm,router} from '@inertiajs/vue3';
import Layout from '../Components/Layout.vue';
import Plans from '../Components/Plans.vue';
import SiteIcon from '../Components/SiteIcon.vue';
import Icon from '../Components/Icon.vue';
const props=defineProps({supportTickets:Array,requestedPlan:String,requestedMonths:Number,plans:Array,sites:Array,telegramAvailable:Boolean,telegramBot:String,requests:Array});
const page=usePage(),support=useForm({subject:'',message:''}),activation=useForm({token:''}),verification=useForm({token:''}),telegram=useForm({password:''}),site=useForm({name:'',url:''}),subscription=useForm({plan:props.requestedPlan||'plus',months:props.requestedMonths||1});
const date=v=>v?new Date(v).toLocaleString():'—';
</script>
<template><Layout><section class="section"><p class="eyebrow">YOUR PERSONAL CINEMA</p><h1 class="page-title">Hello, {{ page.props.user.name }}.</h1><p class="muted">Your stories, your membership, your movie night.</p><div class="dashboard-grid">
<article v-if="!page.props.access.telegram_verified" class="panel onboarding"><span class="pill">ACCOUNT VERIFICATION</span><h2>Verify your Telegram account</h2><p class="muted">Registered Telegram username: <b>@{{ page.props.user.telegram_username || 'not set' }}</b>. Verification connects subscription delivery and password recovery to your private chat.</p><p v-if="!telegramAvailable" class="fine">Telegram setup is pending. Please contact the owner.</p><div v-else class="onboarding-grid"><div><h3>1. Open the bot</h3><p class="muted">Use the Telegram account with the username shown above, then press Start.</p><a v-if="page.props.flash.telegram_link" :href="page.props.flash.telegram_link" target="_blank" rel="noopener noreferrer" class="button">Open Telegram bot <Icon name="arrow" :size="17" /></a><a v-else-if="page.props.access.telegram_linked" :href="'https://t.me/'+telegramBot" target="_blank" rel="noopener noreferrer" class="button">Open bot · send /account ↗</a><form v-else @submit.prevent="telegram.post('/telegram/link',{onFinish:()=>telegram.reset('password')})"><label>Confirm your account password<input v-model="telegram.password" type="password" autocomplete="current-password" required /></label><button class="button outline" :disabled="telegram.processing">Generate a secure bot link ↗</button><p v-for="error in telegram.errors" class="error">{{ error }}</p></form></div><form class="verify-form" @submit.prevent="verification.post('/telegram/verify',{onSuccess:()=>verification.reset()})"><h3>2. Enter the verification code</h3><label>Code from your private Telegram chat<input v-model="verification.token" autocomplete="one-time-code" placeholder="Paste the code from the bot" required /></label><p v-for="error in verification.errors" class="error">{{ error }}</p><button class="button" :disabled="verification.processing">Verify account <Icon name="check" :size="17" /></button><p class="fine">The code expires in 10 minutes. Send /account to the bot for a new one.</p></form></div></article>
<article class="panel"><span class="pill">{{ page.props.access.suspended?'SUSPENDED':page.props.access.telegram_required?'VERIFY TELEGRAM':page.props.access.active?'ACTIVE':'MEMBERSHIP ENDED' }}</span><h2>{{ page.props.access.trial?'Your free day':page.props.access.plan+' membership' }}</h2><p class="muted">{{ page.props.access.suspended?'Contact the owner to reactivate your account.':'Access ends: '+date(page.props.access.ends_at) }}</p><a href="/#download" class="button outline">Download the browser <Icon name="download" :size="17" /></a><p v-if="page.props.access.telegram_verified" class="fine">✓ Telegram verified · Your codes arrive in your private bot chat.</p></article>
<form class="panel" @submit.prevent="activation.post('/subscription/activate',{onSuccess:()=>activation.reset()})"><h3>Activate your membership</h3><p class="muted">When the owner approves your payment, the bot sends your personal activation code. Paste it here or in the desktop browser.</p><label>Subscription code<input v-model="activation.token" required placeholder="Your code from Telegram" autocomplete="one-time-code" /></label><p class="error" v-for="error in activation.errors">{{ error }}</p><button class="button" :disabled="activation.processing">Activate membership ↗</button></form>
<form class="panel" @submit.prevent="subscription.post('/subscription/request')"><span class="eyebrow">YOUR NEXT MOVIE NIGHT</span><h3>Request a subscription</h3><p class="muted">Choose a plan. The owner reviews your request and payment, then the bot delivers your code. No automatic charges.</p><label>Membership plan<select v-model="subscription.plan"><option v-for="plan in plans" :key="plan.id" :value="plan.id">{{ plan.name }} · {{ (subscription.months===12?plan.yearly:plan.monthly).toLocaleString() }} IQD</option></select></label><label>Billing period<select v-model="subscription.months"><option :value="1">1 month</option><option :value="12">1 year · save 5%</option></select></label><p v-if="!page.props.access.telegram_verified" class="fine">Verify your Telegram above to send your request.</p><p v-for="error in subscription.errors" class="error">{{ error }}</p><button class="button" :disabled="subscription.processing || !page.props.access.telegram_verified || requests.some(r=>r.status==='pending')">{{ requests.some(r=>r.status==='pending')?'Request awaiting owner':'Send plan request ↗' }}</button><div v-for="request in requests" :key="request.id" class="request-row"><div><b>{{ request.plan }} · {{ request.months===12?'1 year':'1 month' }}</b><small>{{ request.amount.toLocaleString() }} IQD · {{ date(request.created_at) }}</small></div><span class="pill">{{ request.status }}</span></div></form>
<article class="panel"><h3>Your personal websites</h3><p class="muted">{{ page.props.access.custom_site_limit ? sites.length+' / '+page.props.access.custom_site_limit+' websites · icons load automatically':'Plus and Pro let you bring your own free movie websites.' }}</p><form v-if="page.props.access.active && page.props.access.custom_site_limit" @submit.prevent="site.post('/sites',{onSuccess:()=>site.reset()})"><label>Website name<input v-model="site.name" required maxlength="80" /></label><label>Website URL<input v-model="site.url" required placeholder="example.com or https://example.com" inputmode="url" /></label><p v-for="error in site.errors" class="error">{{ error }}</p><button class="button outline" :disabled="site.processing">Add website +</button></form><div v-for="item in sites" :key="item.id" class="saved-site"><SiteIcon :site="item" /><div><b>{{ item.name }}</b><small>{{ item.url }}</small></div><button v-if="page.props.access.active && page.props.access.custom_site_limit" @click="router.patch('/sites/'+item.id,{favorite:!item.favorite})" :aria-label="item.favorite?'Remove favorite':'Favorite website'">{{ item.favorite?'★':'☆' }}</button><button @click="router.delete('/sites/'+item.id)">Remove</button></div></article>
<article class="panel"><h3>Support</h3><p class="muted">Send a message to the owner. Replies are saved here and delivered to your verified Telegram chat. You can also send /support followed by a message to the bot.</p><form @submit.prevent="support.post('/support',{onSuccess:()=>support.reset()})"><label>Subject<input v-model="support.subject" required maxlength="100" /></label><label>Your message<textarea v-model="support.message" required maxlength="2000" rows="4"></textarea></label><p v-for="error in support.errors" class="error">{{error}}</p><button class="button outline" :disabled="support.processing">Send support message ↗</button></form><div v-for="ticket in supportTickets" :key="ticket.id" class="support-ticket"><b>#{{ticket.id}} · {{ticket.subject}}</b><p>{{ticket.message}}</p><p v-if="ticket.reply"><b>Owner:</b> {{ticket.reply}}</p><small>{{ticket.status==='failed'?'Reply saved · Telegram delivery pending':ticket.status}} · {{date(ticket.created_at)}}</small></div></article></div><p class="fine">Password help? Send /reset to your linked Telegram bot, then use the reset form.</p></section><Plans :plans="plans" /></Layout></template>
